---
# Site Configuration
# ==================
- hosts: all
  tasks:
    - name: determine interface
      set_fact: ipv4_address="{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
      tags:
        - update-hosts

- hosts: all
  sudo: true
  roles:
    - common
    - oracle_jdk
    - system_user
